import Head from "next/head";
// import { useEffect } from "react";
// import tw from "twin.macro";
import { Hero } from "@components/partials/Hero";
import { Navbar } from "@components/partials/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-main-dark">
        <Navbar />
        <Hero />
        <div className="bg-white bg-opacity-5">
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sapiente recusandae iste nesciunt tenetur incidunt odio sunt fugiat, id pariatur officiis quibusdam asperiores, dolores magni? Dolore, sit inventore nobis at quidem pariatur consectetur ut ipsum eum sapiente, doloremque, repellendus aut odio incidunt ducimus voluptatibus nulla vitae est? Saepe reiciendis minus quae beatae corrupti! Cum, eligendi, voluptates perspiciatis sit iste quo quos commodi at quis dolor eum, in illum nobis eos dolorem. Adipisci, eveniet quae, voluptate inventore dignissimos commodi explicabo sapiente voluptas minus excepturi eius dolorum dolorem praesentium architecto officiis, molestiae ipsum libero in dolores! Aut quasi omnis ducimus, vitae nulla distinctio.
        </div>
      </main>
    </>
  );
}

// let MainHome = tw.main`
//   opacity-100
// `;
