import Head from "next/head";
import { Navbar } from "@components/partials/Navbar";
import Link from "next/link";
import { useEffect, useState } from "react";
import Image from "next/image";

export default function TestNavbar() {
    const [openMenu, setOpenMenu] = useState(false);

    const handleMenu = () => {
        setOpenMenu(!openMenu)
    };
    useEffect(() => {
        if (openMenu) {
            document.body.style.overflow = "hidden";
        } else {
            document.body.style.overflow = "auto";
        }
    }, [openMenu])

    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="">
                <nav className={`w-full ${openMenu ? 'bg-blue-200 md:bg-transparent min-h-screen md:min-h-full' : 'bg-transparent'} flex items-center md:justify-between md:px-36 px-12 flex-col md:flex-row fixed`}>
                    <div className="w-full md:w-auto flex items-center justify-between h-[88px]">
                        <span>Logo</span>
                        <div className="md:hidden block" onClick={handleMenu}>
                            {openMenu ? <div className="w-5 h-6 bg-red-500"></div> : <div className="w-5 h-6 bg-blue-500"></div>}
                        </div>
                    </div>
                    <div className={`w-full ${openMenu ? 'flex' : 'md:flex hidden'} flex-col md:flex-row justify-center items-center gap-7 navbar-item`}>
                        <Link href={"/"}>
                            <a>Home</a>
                        </Link>
                        <Link href={"/test2"}>
                            <a>Testing 2</a>
                        </Link>
                        <Link href={"/test3"}>
                            <a>Testing 3</a>
                        </Link>
                        <div className="md:hidden block">
                            <Link href={"/"}>
                                <a>Keluar</a>
                            </Link>
                        </div>
                    </div>
                    <div className="hidden md:block">
                        <Link href={"/"}>
                            <a>Keluar</a>
                        </Link>
                    </div>
                </nav>

                <div className="mb-10">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia explicabo a, non ullam tempore rem molestiae nesciunt officiis excepturi ad architecto et eaque rerum atque? Unde veniam nisi totam aut facere dolores nam error, architecto quidem eos beatae temporibus tempora, sequi vitae esse eius officia, aperiam doloribus id. Optio reiciendis natus, veritatis, dolor consectetur perspiciatis molestias adipisci accusamus porro facere impedit debitis dolores similique! Esse consequatur, nihil autem reprehenderit sunt minima aut officia dicta porro nobis quisquam, dolorem, eligendi cum ducimus facilis. Cupiditate numquam maiores minima possimus. Tenetur dignissimos a quo quam doloribus aspernatur non, ex modi. Aliquam consequatur doloremque, nostrum ad voluptate, dolorum sapiente repellat culpa voluptatum eveniet nobis itaque at explicabo eum enim facere beatae tempore harum. Possimus voluptatibus nemo beatae blanditiis tempora dolorem, dolor excepturi modi! Ea nulla sit id, obcaecati tenetur omnis nemo magni asperiores? Inventore, quod repellendus molestiae quisquam repellat fuga odio quam beatae qui modi necessitatibus excepturi, cumque eum eaque sit ut sequi placeat! Consequatur voluptatum dignissimos doloremque, id hic quasi sint officiis ducimus veniam qui, temporibus saepe nemo quidem illum maiores voluptas consequuntur eius. Sit eveniet atque aperiam accusantium! Perspiciatis, aliquid! Ipsa voluptas reiciendis velit asperiores placeat iusto, dolores voluptates sequi nemo quas illo labore rem facilis odio corporis quidem. Repellat doloribus nulla maxime, modi porro obcaecati qui sapiente alias omnis sint voluptates expedita quasi architecto officia illo reiciendis cupiditate debitis consectetur nemo quisquam harum quos mollitia. Repellat qui totam perferendis aspernatur doloribus illum iusto nam pariatur. Eveniet rem corporis sint laborum consequuntur repellendus? Molestias tempore eum ullam minus quibusdam reprehenderit dolorem animi cum voluptate, adipisci officia voluptatibus dicta esse porro aut culpa doloremque quasi, aliquid, facere id voluptates ex sit! Reiciendis doloremque fugiat blanditiis delectus incidunt nobis voluptatem quam perferendis sint necessitatibus sequi ipsum quisquam recusandae, quod nam ducimus accusantium nihil autem. Quam animi inventore molestias suscipit sint voluptatibus esse iusto natus tempora distinctio, ducimus ipsa incidunt ipsum modi dolorum quibusdam, tenetur ea, tempore voluptatem voluptates! Omnis, repellendus, animi rem, itaque laudantium fugit nostrum sequi mollitia atque sunt perferendis molestias error assumenda! Earum enim harum praesentium laborum molestias possimus vero, sequi alias rerum, quos maiores distinctio recusandae nostrum amet odio, corrupti voluptates nemo maxime aut fuga facere magni. Asperiores voluptas explicabo mollitia non! Dolore aperiam assumenda iusto dignissimos velit fugiat tempora nulla debitis quisquam consequuntur eligendi quasi perspiciatis odit ratione, rerum quidem accusamus quas pariatur numquam sunt necessitatibus autem ea nesciunt? Nobis temporibus qui, assumenda nam, facilis deleniti culpa sit commodi at fugit, animi iusto. Laborum magnam odit a harum itaque libero magni blanditiis eaque dolore, possimus animi ut culpa. Magni deleniti rem impedit, natus velit, ea facere repellat iure quidem mollitia molestias maxime animi nobis provident! Et, optio commodi deserunt harum aliquid dolorum eius voluptatem architecto vel numquam quae repellendus totam, nam accusantium sapiente dolore suscipit minima autem atque. Laboriosam numquam nulla laborum necessitatibus repellat enim ex natus perspiciatis blanditiis, ad voluptate ipsa illum delectus est minima modi nam consequuntur explicabo facilis! Excepturi natus in alias asperiores ex exercitationem porro, harum, amet, rerum officiis obcaecati! Beatae dignissimos ipsum nobis a earum repellendus iusto perspiciatis? Repellat doloribus veritatis nulla iusto at architecto assumenda perspiciatis atque perferendis recusandae libero quasi, saepe magnam? Repellendus laudantium incidunt veritatis rem aut quidem, doloribus, repudiandae corporis voluptatum nostrum laboriosam dolorem architecto nobis excepturi voluptas saepe similique dolores officia, eaque quas nihil ipsum consequatur iure accusantium. Voluptatem perferendis, vitae ratione assumenda magni autem tempore sunt praesentium esse labore, reprehenderit quis consequatur est quam mollitia nam deserunt sint, consectetur voluptates asperiores aliquam eligendi nisi. Doloribus accusamus voluptatibus assumenda voluptas, adipisci natus, vitae quod, consequuntur unde ea nam iste et ipsum minima eum alias eius veritatis. Hic unde quod ullam molestiae. Reprehenderit quisquam nostrum, adipisci dignissimos sequi ut, aliquid debitis, illo omnis excepturi numquam! Veritatis recusandae voluptate dolore alias ab explicabo itaque harum ipsum voluptatum quia, unde minima molestiae inventore cupiditate deleniti fugiat corporis. Dignissimos debitis exercitationem repudiandae quidem. Laboriosam nostrum reiciendis voluptates assumenda, aliquam id excepturi sequi nemo nisi corporis omnis saepe sint at perferendis autem ipsum enim architecto est perspiciatis quae rem cupiditate. Nisi repudiandae, nobis tenetur excepturi cumque praesentium quos eligendi pariatur illum molestiae optio unde. Cupiditate delectus veritatis labore dignissimos, ducimus eos dolorum quidem vitae eligendi consequatur ipsam alias a ab, at et sed qui assumenda totam aliquid doloribus repellendus aperiam excepturi. Aspernatur rem magni illum voluptatem iste, architecto officiis praesentium libero in quas ipsa nam dolorum ut dolores aut dicta sit recusandae vero! Iste laborum, ut officiis necessitatibus natus aliquam consequatur delectus facilis quos, accusantium quas. Delectus laboriosam error repellat iure reprehenderit nesciunt illo necessitatibus, maxime suscipit, voluptatem, quibusdam vero cum! Iusto doloribus omnis nostrum et veniam similique molestiae quaerat aliquid repellendus, harum libero vitae quos inventore temporibus, obcaecati itaque expedita eos tempore reprehenderit ducimus! Harum dolor repellat ducimus adipisci id fuga ipsum incidunt! Iste aliquid, odit nihil esse quaerat temporibus maxime! Corrupti quis obcaecati quam maiores ipsum explicabo exercitationem? Doloribus placeat labore rem voluptate magnam, suscipit deserunt non eum quos facere nisi reprehenderit molestias tenetur aliquam, assumenda numquam impedit laudantium libero ab dolore magni ad iste. Odit architecto laboriosam officiis eum omnis, sunt, dolorem dolore aspernatur eius, tempora explicabo natus. Porro laboriosam consequatur, sequi excepturi sed perspiciatis explicabo nobis officiis. Eos aperiam neque quis quo, molestiae fugit laborum error dicta cum saepe rerum ad vero aliquid deserunt! Voluptatum animi, architecto laboriosam mollitia, quas consequuntur nam nobis, praesentium provident perspiciatis adipisci quam rem doloribus esse impedit sunt nemo ullam molestias tempora iste quis sint quibusdam cumque. Deleniti culpa in ipsa libero dolores earum adipisci quo, non vitae quis nisi eligendi corrupti dicta itaque. Voluptate expedita nesciunt doloremque tenetur cumque cupiditate illo animi reiciendis consectetur amet consequatur officia praesentium laborum porro officiis itaque, soluta at ipsum dignissimos! Voluptate assumenda facilis nihil labore enim, veniam error rerum perferendis. Dolorem voluptatum aliquid error amet sed eum perferendis quia quas temporibus nostrum aspernatur non, sequi odio incidunt quasi, necessitatibus, ullam laboriosam. Recusandae aspernatur deleniti cupiditate beatae repellendus repellat ipsa vitae iusto blanditiis animi. Iure a ea impedit vitae nisi.
                </div>
                <div className="p-10">
                    <Nyobain status={'belum dimulai'} />
                    <Nyobain status={'proses'} />
                    <Nyobain status={'selesai'} />
                </div>

                <div className="p-20">
                    <UploadImages />
                    tes
                </div>


            </main>
        </>
    );
}

const Nyobain = ({ status }) => {
    return (
        <div className={`flex gap-x-4 items-center capitalize 
        ${status === 'belum dimulai' && 'text-red-500' || status === 'proses' && 'text-blue-500' || status === 'selesai' && 'text-green-500'} `}>
            {status}
            <div className={`w-4 h-4 rounded-full ${status === 'belum dimulai' && 'bg-red-500' || status === 'proses' && 'bg-blue-500' || status === 'selesai' && 'bg-green-500'} }`} />
        </div>
    )
}

const UploadImages = () => {
    const [image, setImage] = useState(''); //mengambil path image yg diupload
    const [imagePreview, setImagePreview] = useState(''); //menampilkan image yang diupload
    // const [images, setImages] = useState([]);
    // const [imageURLs, setImageURLs] = useState([]);

    // useEffect(() => {
    //     if(images.length < 1) return;
    //     const newImageUrls = [];
    //     images.forEach(image => newImageUrls.push(URL.createObjectURL(image)));
    //     setImageURLs(newImageUrls);
    // }, [images]);

    // const onImageChange = (e) => {
    //     setImages([...e.target.files]);
    // }

    // console.log("imageURL: ", imageURLs);
    // console.log("images: ", images);

    return(
        <div className="w-full grid grid-cols-3 gap-5">
            {/* {imageURLs === [] ? (
                <button className=" border-none focus:outline-none ring-2 ring-blue-200 relative h-52 w-full flex justify-center items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 text-blue-200" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
            <input type="file" accept="image/*" onChange={onImageChange} className="absolute bg-red-50 inset-0 cursor-pointer opacity-0" />
        </button>
            ) : (
                <>
            { imageURLs.map(imageSrc => <img src={imageSrc} />)}
                </>
            )}
             */}

<div className="text-center image-upload">
                  <label htmlFor="avatar">
                    <Image src={imagePreview} className="img-load" alt="upload icon" />
                  </label>
                  <input
                    id="avatar"
                    type="file"
                    name="avatar"
                    accept="image/png, image/jpeg"
                    onChange={(event) => {
                      const img = event.target.files[0]
                      setImagePreview(URL.createObjectURL(img))
                      return setImage(img)
                    }}
                  />
                </div>

        </div>
    )
}